### ISSUE TITLE
[BUG]  validator "totalStake" missing in validatorHistories

### ISSUE THREAD

**Issue by sahilnanda1995** [buidl-labs/yieldscan-backend-ts#11]
# TODO

## 🎯 &nbsp; What is the problem that needs to be solved?
validator "totalStake" missing in validatorHistories
required for nominator daily earnings

Try to be as specific as possible. Think about falsifiable outcomes.

**Refer:** [SMART Goal Examples](https://www.thebalancesmb.com/smart-goal-examples-2951827)

### 🗒 &nbsp; Summary
A brief overview of the problem to be solved. Include all relevant data points.

### ✅ &nbsp; Outcomes
- [ ] Add totalStake parameter/key in validator history collection

**Comment by saumyakaran** [comment]
@sahilnanda1995 I can see that you've removed the ETA section on this TODO. 

I'm assuming that's probably because you're not working on this right now/don't have an ETA on this yet. 

I should probably have added this in the template itself (will update it after posting this comment) - it would be helpful to add a status on the ETA. 

For example, if there isn't an ETA for this issue, we could add something like "Gaining awareness" (i.e. will update when I have enough awareness) or "Icebox" (i.e. not solving this right now, will update when I pick this issue up).

Would you agree?

**Comment by saumyakaran** [comment]
@sahilnanda1995 

PS - Can we add priority and size labels to this issue?

**Comment by sahilnanda1995** [comment]
@saumyakaran  it already been fixed, probably the [commit message](https://github.com/buidl-labs/yieldscan-backend-ts/commit/6564a2e726a7aa514eea4f0fb8d4e5efb29a7d51) wasn't too clear from me

**Comment by saumyakaran** [comment]
@sahilnanda1995 Ah I see! In that case shall we close this issue?

**Comment by sahilnanda1995** [comment]
it will automatically close when merged to master or develop, I think ;)
